### ISSUE TITLE
Overlay failing to launch

### ISSUE THREAD

**Issue by Goji-Moji** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#1]
When opening ` MH-HP-Overlay.exe ` the command window with flash open for a moment and then instantly close, with the functionality seemingly failing to do anything in the Citra window (ie I never see any HP numbers)

When trying to open the .exe through CMD or Powershell I get the following result:

<img width="824" alt="image" src="https://github.com/user-attachments/assets/10574488-1205-4fb9-a31e-4f1979a8ffae">

and still no hp overlay. Installing the binary extra as per the message doesn't seem to do anything either.

**Comment by Goji-Moji** [comment]
I figured out what the problem was. Needed to install AutoHotKeys—did not see it listed anywhere among requirements for running so I didn't realize I needed to install another program.

You should probably add that to the instructions! But I'm happy to report that it's not a bug as such.

**Comment by Alexander-Lancellott** [comment]
Apologies for the delayed response. It seems that this is indeed a bug, as installing AHK shouldn't be a requirement. The ahk[binary] library from PyPi is supposed to provide the necessary AHK binaries, eliminating the need for users to install AHK separately on Windows. Therefore, I've reopened the issue and will investigate it further. Thank you very much for bringing this to my attention.

**Comment by Alexander-Lancellott** [comment]
With the latest changes I've made, it should no longer be necessary to install AHK separately on Windows. If you'd like, you can uninstall AHK and use the [1.0.1 release](https://github.com/Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator/releases/tag/v1.0.1) I just launched a few minutes ago, which should resolve this issue.
