### ISSUE TITLE
overlay not working for MHXX?

### ISSUE THREAD

**Issue by Goji-Moji** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#2]
Overlay appears to be working properly for 4U and 3U, and it detects XX, but does not appear to be showcasing numbers?

Maybe it's something wrong with my version...?

Tested with 1.0, 1.02 and 1.03

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/1e7ba091-004a-4700-be68-2ab6148285a8">

**Comment by Goji-Moji** [comment]
Found the solution, needed to be patched to 1.4 (or maybe another version) but 1.0 wasn't working

**Comment by Alexander-Lancellott** [comment]
That's strange, I've tested it on my PC, and it works fine on MHXX without any updates. However, if it worked fine for you with version 1.4, I'll leave it as is unless you or someone else needs it for version 1.0 and is willing to help me find the bug
