### ISSUE TITLE
Monster Health not displaying when hungry

### ISSUE THREAD

**Issue by cody-png** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#3]
As the title says, if a monster enters the hunger/exhausted state where it (typically) is drooling, takes long pauses between attacks etc, the health display for that monster will disappear temporarily until said monster either: A. Eats or B. Becomes enraged. 
So far I've only had this issue in MH3U, but that's due to not playing 4U or Gen/XX yet. 
Forgive me if this is known or stated/has a stated solution (I used CTRL+F to search the description, couldn't find anything under hunger or exhaust)

**Comment by Alexander-Lancellott** [comment]
Try using version 1.1.0. I've also been working on fixing the visibility handler for monsters in MH3U, as I had received a similar report about this issue. Let me know if the update resolves it!

**Comment by cody-png** [comment]
1.1.0 has fixed this! Thank you very much.
