### ISSUE TITLE
version 1.1.0 sees MHXX as MH4

### ISSUE THREAD

**Issue by Markesto** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#4]
Version 1.1.0 appears to be seeing MHXX as MH4 
The overlay on the left is version 1.0.3 and on the right is the new version
![muchsus](https://github.com/user-attachments/assets/a7d5e5f2-b889-4e57-9819-e6a82e45968c)

**Comment by Alexander-Lancellott** [comment]
Thank you for reporting this. It seems to happen with the latest Nightly or any other version that likely has a 4, as the Regex I implemented is not very precise. I will fix it in the next release.
