### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ZxCFss** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#5]
When loading from save state while the program is running causing Citra to crash.

**Comment by cody-png** [comment]
Same thing with abandoning a quest. Didn't know the overlay was causing my save state crashes, so I just abandoned a quest without the overlay and it didn't crash, but when overlay is on it'll crash.

**Comment by Alexander-Lancellott** [comment]
Does this crash occur only with version 1.1.0, or also with previous versions ?

**Comment by cody-png** [comment]
It's been occurring since 1.0.3 for me for both cases.

**Comment by Alexander-Lancellott** [comment]
Thank you for the information. I have been able to replicate the bug and will start investigating, although I'm not sure if I'll be able to fix it soon.

**Comment by Alexander-Lancellott** [comment]
Hello, the issue with state loading should have been resolved with release [v1.1.1](https://github.com/Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator/releases/tag/v1.1.1). However, I haven’t been able to replicate or experience the same issue when abandoning a mission, so if v1.1.1 doesn’t fix that problem, I suggest you try adjusting the hp_update_time option (found in config.ini) to values higher than 0.5.

**Comment by cody-png** [comment]
1.1.1 fixes the load state crash as well as crashing after abandoning quests. No need to change HP Update Time.

**Comment by Alexander-Lancellott** [comment]
That sounds good, thanks.
